### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Dreamanchik** [plencka/Spore-Rich-Presence#7]
The Rich Presence is not working on new version of Discord. 
I've downloaded the mod but it still shows the default text like "Playing Spore, 7 minutes elapsed", but thats all.

**Comment by plencka** [comment]
Are you sure ModAPI is working properly?

It appears somebody is using the mod right now properly.
![image](https://user-images.githubusercontent.com/49527545/216142286-a71ca7af-478c-4920-84d1-6f509aed3c5f.png)

1. Have you installed the ModAPI launcher and installed the mod using this software? Does any other mod work properly? 
You haven't specified if the mod ever worked for sure, so I can't be sure if it's related to the new version of Discord.
3. What version of Spore are you using? Steam, Origin, disk version?

**Comment by plencka** [comment]
It has been more than a month since the issue was reported. 

I asked around and according to verified reports, the mod is still functioning and it is probable that it is not connected to the new version of the application. 

If you possess additional information, please feel free to reopen this issue.
